### ISSUE TITLE
Escaped % signs are eliminated

### ISSUE THREAD

**Issue by noah80** [fchauvel/flap#10]
Hi,

I like the script, but it messes up if there is an \% in the file. It will then drop everything beyond the \%, although it is part of the document, which is kind of bad. Any way to fix that?

Example from a table:
Original:
1   & 20 \degree C   & nno    & 0            & 0 \%                    & 0 kWh         \\ 
After flattening:
1   & 20 \degree C   & nein    & 0            & 0 \\

Best

**Comment by fchauvel** [comment]
Hello,

Yes, it is due to the use of regular expression. I'll look at it this week and let you know as soon as I got a fix.

Regards,

Franck

**Comment by fchauvel** [comment]
Hello,

Sorry for the delay, I just push an improvement that fixes the problem in the tests I wrote. I you try the last version directly from the sources, let me know if it does not fix the problem on your side. (See commit 6793c3b)

**Comment by noah80** [comment]
It works for me. Thank you!

**Comment by fchauvel** [comment]
Thanks a lot for the feedback.
