### ISSUE TITLE
Comments replaced by newline cause havoc

### ISSUE THREAD

**Issue by steven-murray** [fchauvel/flap#12]
Hi, 

After applying FLaP to my latex project, I tried compiling the created "merged.tex" file. However, it didn't compile, because it had odd spacing in some of the calls. This is because I have lines like:

```latex
\documentclass[ twoside,openright,titlepage,numbers=noenddot,headinclude,%1headlines,% letterpaper a4paper
                 footinclude=true,cleardoublepage=empty,abstractoff, % <--- obsolete, remove (todo)
                BCOR=5mm,paper=a4,fontsize=11pt,%11pt,a4paper,%
                american,%
                %listof = withchapterentry,
                ]{scrreprt}
```

The commented line gets replaced with a newline, but that won't compile. If however comments are replaced with an empty string, it compiles. I don't know if this would break anything else however.

**Comment by fchauvel** [comment]
This issue requires some investigation, but I get the feeling that we are reaching here the limits of using substitutions using regular expression (on which FLaP is based). I will look further into that and let you know if I can find a fix.

**Comment by steven-murray** [comment]
I don't know about something completely robust, but in the code ``engine.py`` line 173, I just changed the replacement from '\n' to "" and it worked for me.

**Comment by fchauvel** [comment]
I close this issues as [FLaP v0.4.0](https://github.com/fchauvel/flap/releases/v0.4.0) addresses it. Let me know if you face further problems.
