### ISSUE TITLE
subfiles

### ISSUE THREAD

**Issue by steven-murray** [fchauvel/flap#13]
Hi,

Sorry I'm adding a few issues that I found when using this recently all at the same time.

It doesn't seem like FLaP can deal with subfiles? It seems to work fine for my \include statements, but not the subfiles. Is this easy to add?

**Comment by fchauvel** [comment]
Thanks a lot for giving FlaP a try. 

If you refer to the [subfiles package](https://www.ctan.org/pkg/subfiles?lang=en), I confirm that the current version of FLaP does not support it, but I think it's not a big effort to extend it.  I should be able to add next week.

**Comment by steven-murray** [comment]
Thanks for that. Yeah, for some reason I had to use \subfile for putting my appendices in, rather than \include. I can't even remember why now. But it would be awesome to be able to do.

**Comment by fchauvel** [comment]
I close this issues as [FLaP v0.4.0](https://github.com/fchauvel/flap/releases/v0.4.0) addresses it. Let me know if you face further problems.
