### ISSUE TITLE
Appropriate re-naming of files

### ISSUE THREAD

**Issue by steven-murray** [fchauvel/flap#14]
Last issue --

I often have files with the same names in different subdirectories (eg. I include two files with name ``appendix.tex`` from two different chapters). The way things are named now, one will overwrite the other when they are moved to the same directory. The obvious way around this is to rename things with their directory structure in the filename, so eg. ``chapter/figures/figure.pdf`` goes to ``chapter-figures-figure.pdf``. Would that make sense to do?

**Comment by fchauvel** [comment]
Hehe, nice edge case ;-) I confirm that my test suite does not cover this one.
I think the renaming you propose make sense. from the top of my head, implementing something like should be feasible in one week.

**Comment by fchauvel** [comment]
I close this issues as [FLaP v0.4.0](https://github.com/fchauvel/flap/releases/v0.4.0) addresses it. Let me know if you face further problems.
