### ISSUE TITLE
Local packages in subdirectories are not copied

### ISSUE THREAD

**Issue by fchauvel** [fchauvel/flap#22]
According to @gro1729, the traversal of style files that are located in subdirectories seems broken
(see  [Issue #21](https://github.com/fchauvel/flap/issues/21#issuecomment-271572817)).

**Comment by fchauvel** [comment]
A couple of questions:
 * Do you think it is the `\usepackage{input/onimage.sty}` that fails?
 * Did FLaP generate a log file (named `flap.log`)? Is it exists, could you paste it?

**Comment by gro1729** [comment]
Yes, a log-file is generated but it is empty. I fear it's again a
problem with my kind of insertion of pictures.

And by the way:

Calling "flap -v" results in:

Usage: flap [OPTIONS] TEX_FILE OUTPUT

Error: Missing argument "tex_file".

Am 10.01.2017 14:53, schrieb Franck Chauvel:

**Comment by fchauvel** [comment]
The "Error: Missing argument" is normal, as we still must specify the root TeX file and the output directory.
Could you try with: `flap -v 20161208.tex flattened` and let me know the output (if any)?

**Comment by gro1729** [comment]
Yes, it's true. My style-file '|onimage.sty|' is correctly copied, but
none of my included pictures ist found. 

Am 10.01.2017 14:53, schrieb Franck Chauvel:

**Comment by gro1729** [comment]
Sorry!, my fault. "-v" often stands for "version" and not  for "verbose"
Pretty good! That's much better: And my pictures aren't found any longer

FLaP
0.5.0                                                                                                                                  

File                            Line Column LaTeX
Command                                                                                   

-------------------------------------------------------------------------------                                                             

20161208-Zeichnung.tex            14      1
\input{input/000_packages}                                                                      

input/000_packages.tex            44      1
\usepackage[colorinlistoftodos,p...
todonotes.sty                    472      1 \endinput\n%%\n%% End of
file `t...
input/000_packages.tex            84      1 \usepackage{input/onimage}
onimage.sty                      130      1 \endinput\n%%\n%% End of
file `o...
20161208-Zeichnung.tex            15      1 \input{input/010_layout}
20161208-Zeichnung.tex            16      1 \input{input/020_customize}
20161208-Zeichnung.tex            26      4 \input{input/011_layout}
20161208-Zeichnung.tex            32     10 \input{20161208-Grotefeld}
20161208-Grotefeld.tex           167      4
\includegraphics[width=0.275\tex...


Am 10.01.2017 15:21, schrieb Franck Chauvel:

**Comment by gro1729** [comment]
Great, you got it:

  
\includegraphics[width=0.275\textwidth,interpolate]{../VeryLongPathName/Picture}

works, but

   \includegraphics[width=0.275\textwidth,interpolate]{%
        ../VeryLongPathName//Pyrit}

does not!

Am 10.01.2017 15:21, schrieb Franck Chauvel:

**Comment by gro1729** [comment]
One further remark regarding my last email.

I have in mind that my typical kind of include-syntax could be
implemented in FLaP, too.

**Comment by fchauvel** [comment]
I have reproduced this issue and I will look at it later this week.

Meanwhile, a workaround is to move the comment symbol outside the group containing the path, as follows:
```latex
\includegraphics[width=0.275\textwidth,interpolate]%
{ ../VeryLongPathName//Pyrit}
```
This is tested in v0.5.0 (cf. [the associated test case](https://github.com/fchauvel/flap/blob/77b7e2b/tests/acceptance/scenarios/multiline%20commands.yml)).

**Comment by fchauvel** [comment]
Hopefully, Commit 10d2347 fixes this issue.
Could you try it (i.e., installing again from [the sources](https://github.com/fchauvel/flap/archive/master.zip)) and let me know the result?

**Comment by gro1729** [comment]
Hello, much better!


but I have some further issues:


1) In one of my style files I set

\setkomavar{fromlogo}{\includegraphics[width=3cm]{images/Logo}}

In the resulting "merged.tex" I find the same text. The "Logo.png"-File
ist not copied.

2) My style file "onimage.sty" is copied into the
"merged"-Root-Directory, but in "merged.tex" I still find the line
        \usepackage{input/onimage}

3) I have to use Fonts of my company. Thus I have to compile with xetex
or luatex. A Font-Declaration is defined by:
        \setmainfont[
           Path          = ../Fonts/Fontin/ttf/,
           Extension     = .ttf,
           Ligatures     = TeX,
           BoldFont      = Fontin-Bold,
           ItalicFont    = Fontin-Italic,
           SmallCapsFont = Fontin-SmallCaps
        ]{Fontin-Regular}
None of the Fonts is copied into the "merged"-Directory

4) I use one of the KOMA-Script packages, where you can define external
declarations of style information in files with extension ".lco". I do
that in the file "input/sections.lco"
        \documentclass[
          * input/sections*,           
           a4paper,                  
           foldmarks=true,           
           fontsize=12pt,            
           version=last              
        ]{scrlttr2}
The declaration file is not copied into the "merged"-Folder and not
replaced by "sections.lco" inside "merged.tex"

5) I use relative pathnames like: "../VeryLongPathName/Pyrit". 
        \includegraphics[width=0.275\textwidth,interpolate]{%
            .._VeryLongPathName_Pyrit}
On Linux FLaP generates a local file ".._VeryLongPathName_Pyrit" in the
merged-directory. The filename is valid for Linux but not for Windows.
"lualatex" also has trouble with the compilation.

6) In combination with the package "wrapfigure" I had to define some
variables
        \newcounter{figure}
        \makeatletter
           \def\ext@figure{}
        \makeatother
        \newcounter{table}
        \makeatletter
           \def\ext@table{}
        \makeatother
FLaP translates this to
        \newcounter{figure}
        \makeatletter
  
        \makeatother
        \newcounter{table}
        \makeatletter
  
        \makeatother
in the file "merged.tex"

7) Besides "includegraphics"  for instance I use
           \adjincludegraphics[valign=t,width=.9\textwidth,interpolate]{%
              ../VeryLongPathName/Pyrit}
The referenced image-file is not converted. "merged.tex" contains the
same text as the original file.

Regards

Am 11.01.2017 11:11, schrieb Franck Chauvel:

**Comment by fchauvel** [comment]
Thanks a lot for the feedback.
As those are new problems, I close this issue and created a separate one for each.
