### ISSUE TITLE
Local style files are copied but the inclusion directives are not adjusted

### ISSUE THREAD

**Issue by fchauvel** [fchauvel/flap#24]
From @gro1729, [Issue 22](https://github.com/fchauvel/flap/issues/22#issuecomment-271934997):

> My style file "onimage.sty" is copied into the "merged"-Root-Directory, but in "merged.tex" I still find the line \usepackage{input/onimage}

**Comment by fchauvel** [comment]
Hopefully Commit  1fb4cda should fix this.
Just let me know if it does not work.

**Comment by gro1729** [comment]
Great, both of your last changes are working! I think issues #27 and #24
can be closed.

Am 18.01.2017 10:51, schrieb Franck Chauvel:

**Comment by fchauvel** [comment]
Thanks for the feedback.

**Comment by gro1729** [comment]
Gerne!
