### ISSUE TITLE
`\def`are stripped out

### ISSUE THREAD

**Issue by fchauvel** [fchauvel/flap#28]
From @gro1729, [Issue 22](https://github.com/fchauvel/flap/issues/22#issuecomment-271934997):

> In combination with the package "wrapfigure" I had to define some variables:
````latex
\newcounter{figure} 
\makeatletter 
\def\ext@figure{} 
\makeatother 
\newcounter{table} 
\makeatletter 
\def\ext@table{} 
\makeatother 
````
> FLaP translates this to :
````latex
\newcounter{figure} 
\makeatletter 
\makeatother 
\newcounter{table} 
\makeatletter 
\makeatother
````
 in the file "merged.tex"

**Comment by fchauvel** [comment]
Hopefully, Commit 357022c should fix this issue. 
@gro1729, could you give it a try and let me know?

**Comment by gro1729** [comment]
I get:
 
    \makeatletter
       \def\ext@figure{}
    \makeatother
    \newcounter{table}
    \makeatletter
       \def\ext@table{}
    \makeatother

in the file "merged.tex". Thanks.

Are there still any other issues I could try?

Best Regards
Andreas

P.S.: Is it possible to define via commandline option the name of the
output-file?

Am 12.01.2017 15:07, schrieb Franck Chauvel:

**Comment by gro1729** [comment]
Sorry, I have another question.

I have several commands re-defined that use the same interface like the
original command. May be, you remember my "\includesvgdf". It would be
great to have a "customer"-needs section, where I can define "behaves
like" and flap handles these command automagically automatically.

What do you think?

Regards from Andreas

Am 12.01.2017 15:07, schrieb Franck Chauvel:

**Comment by fchauvel** [comment]
Thanks for the feedback. I'll close this very issue then.

I am not sure I understand what you would like to do with `\includesvgdf`. Could this be the idea as in Issue #16?

**Comment by gro1729** [comment]
/I do not think, that it is the same issue./

What I would like to have is an interface for my personal LaTeX-macros
in FLaP. For instance: "adjincludegraphics" is not implemented in the
"graphicx"-package. But this official TeXLive- package implements
"adjincludegraphics" with the same 'signature' like 'includegraphics'.
As I have understood, you would implement the use of
"adjincludegraphics" as an enhancement in the 'kernel'-implementation of
FLaP.

You will not do this each time a new package (like my personal
includesvgpdf- package) is implemented? And that's not necessary, I think.

What is my daily (\LaTeX) business? For some of my colleagues I have to
write German, Slovenian, Polisch, .... macros that are mimicing the
behaviour of the English counterpart. "includegraphics" has the
counterpart "fuegeGraphikEin". The German Macro is nothing else than a
textual replacement of the English macro. The interface is the same, but
the ,,implementation'' is different.

What I would like to have is a FLaP-customizing area, where I can
'register'  "fuegeGraphikEin" as my own macro, that has to be handled in
the kernel-implementation like "includegraphics", independent of my
local (La-)TeX-implementation.

Writing this...

/Yes. "includetikz" has more or less the same signature like
"includegraphics", "includesvgpdf", "fuegeGraphikEin"./

Local declaration-files are already (more or less) copied into the
"merged"-directory. The local use of a user-defined macro like
"fuegeGraphikEin" should also work, provided the referenced image-file
would be copied into the merged-directory, which should work for all
macros that are inheriting from, say "includegraphics".

Best regards
Andreas

P.S.: It is very difficult to describe an abstract idea in a foreign
language. Germans have too complex structures of their sentences. I
hope, you will understand my lousy DENglish.

Am 12.01.2017 19:22, schrieb Franck Chauvel:
