### ISSUE TITLE
\endinput

### ISSUE THREAD

**Issue by gro1729** [fchauvel/flap#4]
I use \LaTeX\ based slides since several years --and at least several thousands of slides later, I decided -for my department too- "one slide - one file"

Instead of 
   \begin{comment}
   \end{comment}

I use the
   \endinput 
command

**Comment by fchauvel** [comment]
Do you mean that, FLaP should ignore whatever content is placed between `\begin{comment}`and `end{comment}`? How does the `\endinput`command works?

**Comment by gro1729** [comment]
Find enclosed an example:

   \begin{frame}[t,label=WasWirdGebrauchtUmLaTeXzuVerwenden]
      \frametitle{What do we need to use \LaTeX?}
      \begin{itemize}[<+->]
         \item A text editor (e.g.\ notepad).
         \item A PDF viewer (e.g.\ Adobe Reader).
         \item A \TeX\ distribution (e.g\ MiKTeX or TeX Live).
      \end{itemize}
   \end{frame}

\endinput

(Notepad isn't a particularly good editor. It's much better to
use an editor that's \TeX-aware.)

Everything after having read the keyword "\endinput" is ignored by any \TeX\-\LaTeX\ Compiler. Thus, if the before standing file is not the last one that is appended by "flap", you do not get a "merged presentation".

**Comment by fchauvel** [comment]
Thanks a lot for the input. Seems fairly straightforward to implement. I will let you know when I get something working.
