### ISSUE TITLE
handling of comments in \verb{}

### ISSUE THREAD

**Issue by gro1729** [fchauvel/flap#6]
Hello, inside a fragile slide, I use des "\verb"-Environment

               \begin{center}
                  \verb|\| \verb|{| \verb|}| \verb|%| \verb|~| \verb|&|
                  \verb|#| \verb|$| \verb|^| \verb|_|
               \end{center}

"flap" translates to

               \begin{center}
                  \verb|\| \verb|{| \verb|}| \verb|
                  \verb|#| \verb|$| \verb|^| \verb|_|
               \end{center}

I think, this can be considered to be a "featured bug"

**Comment by fchauvel** [comment]
I think we reach here the limits of the current design, which is based on regular expressions. To handle this, I believe one has to build a proper TeX engine. Along the same lines, I guess that a comment within a `verbatim` environment would be stripped out as well.

**Comment by gro1729** [comment]
I agree. It is a featured bug. After these simple manuell changes the
merged - files compiles.
Great, thanks a lot.

Am 31.08.2015 13:33, schrieb Franck Chauvel:

**Comment by gro1729** [comment]
As a remark, only because you mentioned it. There is another tool, called "plasTeX". As I have understood, this tool works on basis of a \LaTeX\ -Parser, implemented in Python

**Comment by gro1729** [comment]
With your last modifications, this issue probably can be closed

**Comment by fchauvel** [comment]
Thanks for the comment, I had forgotten about this one, but I will check whether it does solve this issue at the same time.

**Comment by fchauvel** [comment]
It works using the 'lookbehind' feature of Python regular expression. So it detects that % is preceded by a '|' and in turn that it is therefore not a comment. Yet, this looks to me more like a quick and dirty fix. Feel free to close this issue if it works in your case.
