### ISSUE TITLE
A matter of taste

### ISSUE THREAD

**Issue by gro1729** [fchauvel/flap#7]
Today, I sent the merged presentation to several colleagues. Some of them use Linux, most of them work with Windows. Conversion from SVG to PDF works properly on Linux. The typical Windows-Installation of Inkscape does not work in combination with TeXLive. As a consequence, I changed "engine.py":

       def extensions_by_priority(self):
   #        return ["svg"]
           return ["pdf"]

**Comment by fchauvel** [comment]
From the top of my head, I guess we could have return both extensions, So that the engine searches for PDF files first, and then searches for SVG files otherwise. Though, I haven't tested that.
````python
return ["svg", "pdf"]
````

**Comment by gro1729** [comment]
The suggested replacement does not seem to work

**Comment by gro1729** [comment]
Sorry, my fault:

      return ["pdf", "svg"]

works
